#!/usr/bin/env bash

# InfMem launcher configuration.
# Override any variable by exporting it before calling scripts/infmem/*.sh.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

PYTHON_BIN="${PYTHON_BIN:-${REPO_ROOT}/.venv/bin/python}"

MCP_SEARCHER_TYPE="${MCP_SEARCHER_TYPE:-bm25}"
MCP_LONG_DOC_MODE="infmem"
MCP_INFMEM_POSITION="${MCP_INFMEM_POSITION:-search}"

if [[ "${MCP_SEARCHER_TYPE}" == "faiss" ]]; then
  DEFAULT_MCP_INDEX_PATH="${REPO_ROOT}/indexes/qwen3-embedding-8b/corpus.shard*.pkl"
  DEFAULT_FAISS_MODEL_NAME="Qwen/Qwen3-Embedding-8B"
  DEFAULT_FAISS_NORMALIZE="1"
else
  DEFAULT_MCP_INDEX_PATH="${REPO_ROOT}/indexes/${MCP_SEARCHER_TYPE}"
  DEFAULT_FAISS_MODEL_NAME=""
  DEFAULT_FAISS_NORMALIZE="0"
fi

ANSWER_MODEL_PATH="${ANSWER_MODEL_PATH:-/work/mingze/models/Tongyi-DeepResearch-30B-A3B}"
ANSWER_VLLM_SERVED_MODEL_NAME="${ANSWER_VLLM_SERVED_MODEL_NAME:-}"
ANSWER_MODEL_NAME="${ANSWER_MODEL_NAME:-${ANSWER_VLLM_SERVED_MODEL_NAME:-${ANSWER_MODEL_PATH}}}"

INFMEM_MODEL_PATH="${INFMEM_MODEL_PATH:-/work/mingze/models/qwen4b_infmem_earlystop_stage2/global_step_150/huggingface}"
INFMEM_VLLM_SERVED_MODEL_NAME="${INFMEM_VLLM_SERVED_MODEL_NAME:-}"
INFMEM_MODEL_NAME="${INFMEM_MODEL_NAME:-${INFMEM_VLLM_SERVED_MODEL_NAME:-${INFMEM_MODEL_PATH}}}"

MODEL_PATH="${MODEL_PATH:-${ANSWER_MODEL_PATH}}"
MODEL_NAME="${MODEL_NAME:-${ANSWER_MODEL_NAME}}"

QUERY_TEMPLATE="${QUERY_TEMPLATE:-QUERY_TEMPLATE_NO_GET_DOCUMENT}"
AGENT_MAX_TOKENS="${AGENT_MAX_TOKENS:-10000}"

ANSWER_VLLM_CUDA_VISIBLE_DEVICES="${ANSWER_VLLM_CUDA_VISIBLE_DEVICES:-0,1,2,3}"
ANSWER_VLLM_HOST="${ANSWER_VLLM_HOST:-127.0.0.1}"
ANSWER_VLLM_PORT="${ANSWER_VLLM_PORT:-6008}"
ANSWER_VLLM_TENSOR_PARALLEL_SIZE="${ANSWER_VLLM_TENSOR_PARALLEL_SIZE:-4}"
ANSWER_VLLM_MAX_MODEL_LEN="${ANSWER_VLLM_MAX_MODEL_LEN:-131072}"
ANSWER_VLLM_REASONING_PARSER="${ANSWER_VLLM_REASONING_PARSER:-qwen3}"
ANSWER_VLLM_ROPE_SCALING="${ANSWER_VLLM_ROPE_SCALING:-}"
ANSWER_VLLM_ENABLE_REASONING="${ANSWER_VLLM_ENABLE_REASONING:-1}"
ANSWER_VLLM_GPU_MEMORY_UTILIZATION="${ANSWER_VLLM_GPU_MEMORY_UTILIZATION:-}"
ANSWER_MODEL_SERVER_URL="${ANSWER_MODEL_SERVER_URL:-http://${ANSWER_VLLM_HOST}:${ANSWER_VLLM_PORT}/v1}"

INFMEM_VLLM_CUDA_VISIBLE_DEVICES="${INFMEM_VLLM_CUDA_VISIBLE_DEVICES:-4,5,6,7}"
INFMEM_VLLM_HOST="${INFMEM_VLLM_HOST:-127.0.0.1}"
INFMEM_VLLM_PORT="${INFMEM_VLLM_PORT:-8001}"
INFMEM_VLLM_TENSOR_PARALLEL_SIZE="${INFMEM_VLLM_TENSOR_PARALLEL_SIZE:-4}"
INFMEM_VLLM_MAX_MODEL_LEN="${INFMEM_VLLM_MAX_MODEL_LEN:-40960}"
INFMEM_VLLM_REASONING_PARSER="${INFMEM_VLLM_REASONING_PARSER:-qwen3}"
INFMEM_VLLM_ROPE_SCALING="${INFMEM_VLLM_ROPE_SCALING:-}"
INFMEM_VLLM_ENABLE_REASONING="${INFMEM_VLLM_ENABLE_REASONING:-0}"
INFMEM_VLLM_GPU_MEMORY_UTILIZATION="${INFMEM_VLLM_GPU_MEMORY_UTILIZATION:-}"
INFMEM_MODEL_SERVER_URL="${INFMEM_MODEL_SERVER_URL:-http://${INFMEM_VLLM_HOST}:${INFMEM_VLLM_PORT}/v1}"

MCP_INDEX_PATH="${MCP_INDEX_PATH:-${DEFAULT_MCP_INDEX_PATH}}"
MCP_HOST="${MCP_HOST:-127.0.0.1}"
MCP_PORT="${MCP_PORT:-8380}"
MCP_TRANSPORT="${MCP_TRANSPORT:-sse}"
MCP_K="${MCP_K:-5}"
MCP_SNIPPET_MAX_TOKENS="${MCP_SNIPPET_MAX_TOKENS:-1024}"
MCP_MODEL_NAME="${MCP_MODEL_NAME:-${DEFAULT_FAISS_MODEL_NAME}}"
MCP_NORMALIZE="${MCP_NORMALIZE:-${DEFAULT_FAISS_NORMALIZE}}"
MCP_INF_MEM_MODEL="${MCP_INF_MEM_MODEL:-${INFMEM_MODEL_NAME}}"
MCP_INF_MEM_MODEL_SERVER="${MCP_INF_MEM_MODEL_SERVER:-${INFMEM_MODEL_SERVER_URL}}"
MCP_INF_MEM_TIMEOUT_SECONDS="${MCP_INF_MEM_TIMEOUT_SECONDS:-120.0}"
MCP_INF_MEM_MAX_RECURRENT_STEPS="${MCP_INF_MEM_MAX_RECURRENT_STEPS:-4}"

TONGYI_PORT="${TONGYI_PORT:-${ANSWER_VLLM_PORT}}"
TONGYI_NUM_THREADS="${TONGYI_NUM_THREADS:-10}"
TONGYI_TEMPERATURE="${TONGYI_TEMPERATURE:-0.85}"
TONGYI_TOP_P="${TONGYI_TOP_P:-0.95}"
TONGYI_PRESENCE_PENALTY="${TONGYI_PRESENCE_PENALTY:-1.1}"
TONGYI_STORE_RAW="${TONGYI_STORE_RAW:-0}"
if [[ -z "${TONGYI_TOOLSET+x}" ]]; then
  if [[ "${MCP_INFMEM_POSITION}" == "visit" ]]; then
    TONGYI_TOOLSET="custom"
  else
    TONGYI_TOOLSET="standard"
  fi
fi

INFMEM_POSITION_RUN_SUFFIX="${INFMEM_POSITION_RUN_SUFFIX:-}"
if [[ -z "${INFMEM_POSITION_RUN_SUFFIX}" ]]; then
  case "${MCP_INFMEM_POSITION}" in
    visit)
      INFMEM_POSITION_RUN_SUFFIX="_visit_infmem"
      ;;
    memory_control)
      INFMEM_POSITION_RUN_SUFFIX="_memctrl_infmem"
      ;;
    *)
      INFMEM_POSITION_RUN_SUFFIX=""
      ;;
  esac
fi

ANSWER_MODEL_BASENAME="${ANSWER_MODEL_BASENAME:-$(basename "${ANSWER_MODEL_PATH}")}"
TONGYI_TOOLSET_RUN_SUFFIX="${TONGYI_TOOLSET_RUN_SUFFIX:-}"
if [[ -z "${TONGYI_TOOLSET_RUN_SUFFIX}" && "${TONGYI_TOOLSET}" == "custom" ]]; then
  TONGYI_TOOLSET_RUN_SUFFIX="_custom"
fi
RUN_TAG="${RUN_TAG:-${MCP_SEARCHER_TYPE}_${MCP_LONG_DOC_MODE}${TONGYI_TOOLSET_RUN_SUFFIX}${INFMEM_POSITION_RUN_SUFFIX}}"
RUN_NAME="${RUN_NAME:-${ANSWER_MODEL_BASENAME}_${RUN_TAG}}"

ANSWER_VLLM_LOG_PATH="${ANSWER_VLLM_LOG_PATH:-${REPO_ROOT}/logs/infmem/${RUN_NAME}_answer_vllm.log}"
ANSWER_VLLM_LAUNCH_NAME="${ANSWER_VLLM_LAUNCH_NAME:-infmem_${RUN_NAME}_answer_vllm}"
INFMEM_VLLM_LOG_PATH="${INFMEM_VLLM_LOG_PATH:-${REPO_ROOT}/logs/infmem/${RUN_NAME}_memory_vllm.log}"
INFMEM_VLLM_LAUNCH_NAME="${INFMEM_VLLM_LAUNCH_NAME:-infmem_${RUN_NAME}_memory_vllm}"
MCP_LOG_PATH="${MCP_LOG_PATH:-${REPO_ROOT}/logs/infmem/${RUN_NAME}_mcp.log}"
MCP_LAUNCH_NAME="${MCP_LAUNCH_NAME:-infmem_${RUN_NAME}_mcp}"

AGENT_MODEL="${AGENT_MODEL:-${ANSWER_MODEL_NAME}}"
AGENT_MODEL_SERVER="${AGENT_MODEL_SERVER:-${ANSWER_MODEL_SERVER_URL}}"
AGENT_MCP_URL="${AGENT_MCP_URL:-http://${MCP_HOST}:${MCP_PORT}/mcp}"
AGENT_OUTPUT_DIR="${AGENT_OUTPUT_DIR:-${REPO_ROOT}/runs/infmem/${RUN_NAME}}"
AGENT_LOG_PATH="${AGENT_LOG_PATH:-${REPO_ROOT}/logs/infmem/${RUN_NAME}.log}"
AGENT_LAUNCH_NAME="${AGENT_LAUNCH_NAME:-infmem_${RUN_NAME}_agent}"

START_ALL_LOG_PATH="${START_ALL_LOG_PATH:-${REPO_ROOT}/logs/infmem/${RUN_NAME}_start_all.log}"
START_ALL_LAUNCH_NAME="${START_ALL_LAUNCH_NAME:-infmem_${RUN_NAME}_start_all}"
