#!/usr/bin/env bash

# Truncate launcher configuration.
# Override any variable by exporting it before calling scripts/truncate/*.sh.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

PYTHON_BIN="${PYTHON_BIN:-${REPO_ROOT}/.venv/bin/python}"

MCP_SEARCHER_TYPE="${MCP_SEARCHER_TYPE:-bm25}"
MODEL_PATH="${MODEL_PATH:-/work/mingze/models/Tongyi-DeepResearch-30B-A3B}"
MODEL_NAME="${MODEL_NAME:-${MODEL_PATH}}"
MCP_LONG_DOC_MODE="truncate"

QUERY_TEMPLATE="${QUERY_TEMPLATE:-QUERY_TEMPLATE_NO_GET_DOCUMENT}"
AGENT_MAX_TOKENS="${AGENT_MAX_TOKENS:-10000}"

VLLM_CUDA_VISIBLE_DEVICES="${VLLM_CUDA_VISIBLE_DEVICES:-0,1,2,3,4,5,6,7}"
VLLM_HOST="${VLLM_HOST:-127.0.0.1}"
VLLM_PORT="${VLLM_PORT:-8000}"
VLLM_MODEL_PATH="${VLLM_MODEL_PATH:-${MODEL_PATH}}"
VLLM_TENSOR_PARALLEL_SIZE="${VLLM_TENSOR_PARALLEL_SIZE:-8}"
VLLM_MAX_MODEL_LEN="${VLLM_MAX_MODEL_LEN:-131072}"
VLLM_REASONING_PARSER="${VLLM_REASONING_PARSER:-qwen3}"
VLLM_ROPE_SCALING="${VLLM_ROPE_SCALING:-}"
VLLM_ENABLE_REASONING="${VLLM_ENABLE_REASONING:-1}"
VLLM_SERVED_MODEL_NAME="${VLLM_SERVED_MODEL_NAME:-}"
VLLM_GPU_MEMORY_UTILIZATION="${VLLM_GPU_MEMORY_UTILIZATION:-}"

MCP_INDEX_PATH="${MCP_INDEX_PATH:-${REPO_ROOT}/indexes/${MCP_SEARCHER_TYPE}}"
MCP_HOST="${MCP_HOST:-127.0.0.1}"
MCP_PORT="${MCP_PORT:-8080}"
MCP_TRANSPORT="${MCP_TRANSPORT:-sse}"
MCP_K="${MCP_K:-5}"
MCP_SNIPPET_MAX_TOKENS="${MCP_SNIPPET_MAX_TOKENS:-1024}"

MODEL_BASENAME="${MODEL_BASENAME:-$(basename "${MODEL_PATH}")}"
RUN_TAG="${RUN_TAG:-${MCP_SEARCHER_TYPE}_${MCP_LONG_DOC_MODE}}"
RUN_NAME="${RUN_NAME:-${MODEL_BASENAME}_${RUN_TAG}}"

VLLM_LOG_PATH="${VLLM_LOG_PATH:-${REPO_ROOT}/logs/truncate/${RUN_NAME}_vllm.log}"
VLLM_LAUNCH_NAME="${VLLM_LAUNCH_NAME:-truncate_${RUN_NAME}_vllm}"
MCP_LOG_PATH="${MCP_LOG_PATH:-${REPO_ROOT}/logs/truncate/${RUN_NAME}_mcp.log}"
MCP_LAUNCH_NAME="${MCP_LAUNCH_NAME:-truncate_${RUN_NAME}_mcp}"

AGENT_MODEL="${AGENT_MODEL:-${VLLM_SERVED_MODEL_NAME:-${MODEL_NAME}}}"
AGENT_MODEL_SERVER="${AGENT_MODEL_SERVER:-http://${VLLM_HOST}:${VLLM_PORT}/v1}"
AGENT_MCP_URL="${AGENT_MCP_URL:-http://${MCP_HOST}:${MCP_PORT}/mcp}"
AGENT_OUTPUT_DIR="${AGENT_OUTPUT_DIR:-${REPO_ROOT}/runs/truncate/${RUN_NAME}}"
AGENT_LOG_PATH="${AGENT_LOG_PATH:-${REPO_ROOT}/logs/truncate/${RUN_NAME}.log}"
AGENT_LAUNCH_NAME="${AGENT_LAUNCH_NAME:-truncate_${RUN_NAME}_agent}"

START_ALL_LOG_PATH="${START_ALL_LOG_PATH:-${REPO_ROOT}/logs/truncate/${RUN_NAME}_start_all.log}"
START_ALL_LAUNCH_NAME="${START_ALL_LAUNCH_NAME:-truncate_${RUN_NAME}_start_all}"
